name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4          

      - name: Setup the project
        run: |
          docker compose up -d
          docker compose exec app bash setup.sh

      - name: Test migrations
        run: |
          docker compose exec app php artisan db:seed
          docker compose exec app php artisan migrate:refresh

      - name: Run tests
        run: |
          docker compose exec app sh -c "rm -rf node_modules package-lock.json && npm install"
          docker compose exec app npm run build
          docker compose exec app php artisan test --parallel --coverage

      - name: Test production setup
        run: |
          docker compose -f docker-compose.prod.yml up -d
          docker compose -f docker-compose.prod.yml exec app bash setup.sh
          docker compose -f docker-compose.prod.yml exec app sh -c "rm -rf node_modules package-lock.json && npm install"
          docker compose -f docker-compose.prod.yml exec app npm run build
          docker compose -f docker-compose.prod.yml exec app php artisan test --parallel --coverage
